= Managing Data Distribution

The partitions of each cache are distributed across all server nodes in accordance with the affinity function implementation.
You can prevent specific nodes from hosting the partitions of a given cache by defining a _node filter_ in the cache configuration.


In addition to node filters, you can control the way backup copies of the partitions are distributed.
//This is useful when you want to ensure that the primary and backup copies are located in different zones in a cloud environment.

== Node Filter
:javaFile: {javaCodeDir}/NodeFilter.java
:xmlFile: code-snippets/xml/node-filter.xml

A node filter allows you to deploy a cache to a subset of server nodes instead of all server nodes (which is the default behavior).
It "filters out" the nodes that you don't want to use.
The node filter can be based on user attributes or node's consistent ID.
If the filter returns `true` for a given node, the cache is deployed on the node.
Otherwise, the node is excluded.

//For example, you can deploy a cache to a subset of server nodes (by default a cache is deployed on _all_ server nodes).
//Node filters can be used with the following functionality:

To create a node filter, implement `IgnitePredicate<ClusterNode>` and provide it in the cache configuration.
Here is an example of a node filter that filters out the nodes with specific consistent IDs.

[tabs]
--
tab:Java[]

[source, java]
----
include::{javaCodeDir}/MyNodeFilter.java[tags=node-filter-example,indent=0]
----
tab:C#/.NET[]
tab:C++[]
--

CAUTION: The class of the node filter must be present in the classpath of all nodes.

When you create a cache with the node filter defined above, the cache is deployed on the set of nodes that are _not_ provided in the node filter's constructor parameter.

[tabs]
--
tab:XML[]
[source, xml]
----
include::{xmlFile}[tags=ignite-config;!discovery, indent=0]
----
tab:Java[]
[source, java]
----
include::{javaFile}[tags=cache-node-filter, indent=0]
----
tab:C#/.NET[]
tab:C++[]
--

== Filtering Nodes by Attributes

`AttributeNodeFilter` is an implementation of `IgnitePredicate<ClusterNode>` that uses user attributes to filter nodes and can be used as a node filter.
The filter checks if a node contains the given attributes with the given values.

The following snippet is an example of using `AttributeNodeFilter` as a node filter for cache deployment. In the example, a cache named "myCache" is deployed on the nodes where the "host_myCache" attribute is set to `true`.

[tabs]
--
tab:XML[]

[source, xml]
----
include::code-snippets/xml/attribute-node-filter.xml[tags=ignite-config;!node-attribute;!discovery,indent=0]
----

tab:Java[]

[source, java]
----
include::{javaFile}[tags=attribute-node-filter, indent=0]
----
tab:C#/.NET[]
tab:C++[]
--

Add the attribute on the nodes where you want to deploy the cache.

[tabs]
--
tab:XML[]
[source, xml]
----
include::code-snippets/xml/attribute-node-filter.xml[tags=ignite-config;!cache-config;!discovery,indent=0]
----

tab:Java[]

[source, java]
----
include::{javaFile}[tags=add-attribute, indent=0]
----
tab:C#/.NET[]
tab:C++[]
--

Note that attributes can also be set via environment variables.


== Backup Filter

:javaFile2: {javaCodeDir}/BackupFilter.java

A backup filter allows you to control how backup copies of the partitions are distributed between the nodes.
//When a backup filter is specified, backup partitions will be created on the nodes that pass the filter.
The backup filter is set via the link:{javadoc_base_url}/org/apache/ignite/cache/affinity/rendezvous/RendezvousAffinityFunction.html#setAffinityBackupFilter-org.apache.ignite.lang.IgniteBiPredicate-[RendezvousAffinityFunction.setAffinityBackupFilter(IgniteBiPredicate<ClusterNode,List<ClusterNode>> affinityBackupFilter),window=_blank] method.
A given partition is assigned to the first node that passes the filter.
The filter is invoked every time Ignite calculates partition distribution (which happens every time the cluster topology changes).

CAUTION: The backup filter is used when `RendezvousAffinityFunction.excludeNeighbors = false`.

//A backup filter can only be used with the default affinity function (`RendezvousAffinityFunction`).

As an example, let's consider an implementation of the backup filter that uses node attributes to decide to which node a backup copy should be assigned.
You can see the source code for this filter in link:https://github.com/gridgain/gridgain/blob/master/modules/core/src/main/java/org/apache/ignite/cache/affinity/rendezvous/ClusterNodeAttributeAffinityBackupFilter.java[ClusterNodeAttributeAffinityBackupFilter.java,window=_blank].
In this implementation, the primary and backup partitions are assigned to the nodes with different values of a given attribute or environment variable.

The following code snippet defines a backup filter that is based on the values of the `AVAILABILITY_ZONE` attribute.
With this configuration, the primary and backup copies of each partition end up in different availability zones (provided the attribute is set correctly).

[tabs]
--
tab:XML[]

[source, xml]
----
include::code-snippets/xml/affinity-backup-filter.xml[tags=ignite-config;!node-attribute;!discovery, indent=0]
----

tab:Java[]
[source, java]
----
include::{javaFile2}[tags=backup-filter, indent=0]
----
tab:C#/.NET[]
tab:C++[unsupported]
--
