exclude: [guidelines.md,  "Gemfile", "Gemfile.lock", README.adoc, "_docs/code-snippets", "_docs/includes", '*.sh']
base_url: /docs
collections:
  docs:
    #    permalink: /docs/{version}/:path:output_ext
    output: true
defaults:
  -
    scope:
      path: ''
    values:
      layout: 'doc'
  -
    scope:
      path: '_docs'
    values:
      toc: ignite 
asciidoctor:
  base_dir: _docs/ 
  attributes:
    source-highlighter: rouge
    stylesdir: assets/css
    version: "latest" 
    base_url: /docs
    imagesdir: /docs
    table-stripes: even
    javadoc_base_url: https://ignite.apache.org/releases/{version}/javadoc
    javaCodeDir: code-snippets/java/src/main/java/org/apache/ignite/snippets
    githubUrl: https://github.com/apache/ignite/tree/master

